.PHONY: run build test tidy docker-up docker-down

run:
	go run main.go

build:
	CGO_ENABLED=0 GOOS=linux go build -o {{.ProjectName}} .

test:
	go test ./...

tidy:
	go mod tidy

docker-up:
	docker-compose up -d

docker-down:
	docker-compose down
