package scaffold

// projectFiles returns a map of file path -> template string for the new project.
// The example module files are NOT listed here — they are generated by the proto
// generator (same engine as `a-kit generate`) from api/example.proto.
func projectFiles(data templateData) map[string]string {
	return map[string]string{
		"go.mod":  tmplGoMod,
		"main.go": tmplMainGo,
		".gitignore":         tmplGitignore,
		"Dockerfile":         tmplDockerfile,
		"docker-compose.yml": tmplDockerCompose,
		"Makefile":           tmplMakefile,
		"README.md":          tmplReadme,

		// global
		"global/configuration.go": tmplGlobalConfiguration,
		"global/errors.go":        tmplGlobalErrors,
		"global/global.go":        tmplGlobalGlobal,

		// middlewares
		"middlewares/middleware.go": tmplMiddleware,

		// utils
		"utils/common/common.go":      tmplUtilsCommon,
		"utils/common/uuid.go":        tmplUtilsUUID,
		"utils/token/token.go":        tmplUtilsToken,
		"utils/validator/validator.go": tmplUtilsValidator,
		"utils/config/config.go":      tmplUtilsConfig,

		// config files
		"config.yaml":         tmplConfigYAML,
		"config.json.example": tmplConfigJSON,

		// mysql sqitch
		"mysql/sqitch.conf": tmplSqitchConf,
		"mysql/sqitch.plan": tmplSqitchPlan,

		// proto definition — the example module is generated from this
		"api/example.proto": tmplExampleProto,
	}
}

// ── go.mod ──────────────────────────────────────────────────────────────────

var tmplGoMod = `module {{.ModuleName}}

go 1.23.0

require (
	github.com/go-playground/validator/v10 v10.27.0
	github.com/golang-jwt/jwt/v5 v5.2.2
	github.com/google/uuid v1.6.0
	github.com/labstack/echo/v4 v4.13.3
	gopkg.in/yaml.v3 v3.0.1
	gorm.io/driver/mysql v1.5.7
	gorm.io/gorm v1.25.12
)
`

// ── main.go ─────────────────────────────────────────────────────────────────

var tmplMainGo = `package main

import (
	"fmt"
	"net/http"

	exampleHTTPHandler "{{.ModuleName}}/example/handler/http"
	exampleRepository "{{.ModuleName}}/example/repository/mysql"
	exampleService "{{.ModuleName}}/example/service"

	"{{.ModuleName}}/global"
	"{{.ModuleName}}/middlewares"
	appconfig "{{.ModuleName}}/utils/config"

	"github.com/labstack/echo/v4"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

func main() {
	var configuration global.Configuration
	if err := appconfig.Load(&configuration); err != nil {
		panic(fmt.Sprintf("failed to load configuration: %v", err))
	}

	dsn := fmt.Sprintf(
		"%s:%s@tcp(%s:%s)/%s?charset=utf8mb4&parseTime=True&loc=Local",
		configuration.DbUser,
		configuration.DbPass,
		configuration.DbHost,
		configuration.DbPort,
		configuration.DbName,
	)
	mysqlDb, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		panic("Error connecting to database")
	}

	e := echo.New()
	mw := middlewares.InitMiddleware([]byte(configuration.PrivateJWTAccessTokenSecret))
	e.Use(mw.ValidateCORS)

	e.GET("/health", func(c echo.Context) error {
		return c.JSON(http.StatusOK, map[string]interface{}{"message": "{{.ProjectName}} is live"})
	})

	// Initialize example module
	exampleRepo := exampleRepository.NewExampleServiceMySQLRepository(mysqlDb)
	exampleSvc := exampleService.NewExampleService(exampleRepo)
	exampleHTTPHandler.NewExampleServiceHandler(e, exampleSvc, mw)

	e.Logger.Fatal(e.Start(fmt.Sprintf(":%s", configuration.HostPort)))
}
`

// ── .env.example ────────────────────────────────────────────────────────────

var tmplEnvExample = `HOST_URL=127.0.0.1
HOST_PORT=9000
DB_HOST=localhost
DB_NAME={{.PackageName}}
DB_USER=root
DB_PASS=
DB_PORT=3306
TIMEOUT_DURATION=30
PRIVATE_JWT_ACCESS_TOKEN_SECRET=your-secret-key
PRIVATE_JWT_REFRESH_TOKEN_SECRET=your-refresh-secret-key
`

// ── .gitignore ───────────────────────────────────────────────────────────────

var tmplGitignore = `.env
config.yaml
config.json
*.exe
*.out
vendor/
{{.ProjectName}}
`

// ── Dockerfile ───────────────────────────────────────────────────────────────

var tmplDockerfile = `# Build stage
FROM golang:1.23-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o {{.ProjectName}} .

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata wget

WORKDIR /root/

COPY --from=builder /app/{{.ProjectName}} .

EXPOSE 9000

CMD ["./{{.ProjectName}}"]
`

// ── docker-compose.yml ───────────────────────────────────────────────────────

var tmplDockerCompose = `version: "3.8"

services:
  app:
    build: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: {{.PackageName}}
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
`

// ── Makefile ─────────────────────────────────────────────────────────────────

var tmplMakefile = `.PHONY: run build test tidy docker-up docker-down

run:
	go run main.go

build:
	CGO_ENABLED=0 GOOS=linux go build -o {{.ProjectName}} .

test:
	go test ./...

tidy:
	go mod tidy

docker-up:
	docker-compose up -d

docker-down:
	docker-compose down
`

// ── README.md ────────────────────────────────────────────────────────────────

var tmplReadme = `# {{.ProjectName}}

A Go service built with clean architecture.

## Getting Started

` + "```bash" + `
cp .env.example .env   # configure your environment
go mod tidy
go run main.go
` + "```" + `

## Project Structure

` + "```" + `
{{.ProjectName}}/
├── main.go
├── global/          # shared config, errors, response types
├── middlewares/     # echo middleware (CORS, JWT)
├── models/          # shared DTOs and DB models
├── utils/           # helpers: common, token, validator
├── mysql/           # database migration scripts (sqitch)
└── example/         # sample module — copy to add new features
    ├── interface.go
    ├── _mock/
    ├── handler/http/
    ├── repository/mysql/
    └── service/
` + "```" + `

## Make Commands

| Command | Description |
|---------|-------------|
| ` + "`make run`" + ` | Run the server |
| ` + "`make build`" + ` | Build binary |
| ` + "`make test`" + ` | Run all tests |
| ` + "`make tidy`" + ` | Tidy Go modules |
| ` + "`make docker-up`" + ` | Start with docker-compose |
| ` + "`make docker-down`" + ` | Stop docker-compose |
`

// ── global/configuration.go ──────────────────────────────────────────────────

var tmplGlobalConfiguration = `package global

type Configuration struct {
	HostUrl                      string ` + "`" + `mapstructure:"host_url"          yaml:"host_url"                          json:"host_url"` + "`" + `
	HostPort                     string ` + "`" + `mapstructure:"host_port"         yaml:"host_port"                         json:"host_port"` + "`" + `
	DbHost                       string ` + "`" + `mapstructure:"db_host"           yaml:"db_host"                           json:"db_host"` + "`" + `
	DbName                       string ` + "`" + `mapstructure:"db_name"           yaml:"db_name"                           json:"db_name"` + "`" + `
	DbUser                       string ` + "`" + `mapstructure:"db_user"           yaml:"db_user"                           json:"db_user"` + "`" + `
	DbPass                       string ` + "`" + `mapstructure:"db_pass"           yaml:"db_pass"                           json:"db_pass"` + "`" + `
	DbPort                       string ` + "`" + `mapstructure:"db_port"           yaml:"db_port"                           json:"db_port"` + "`" + `
	TimeoutDuration              int    ` + "`" + `mapstructure:"timeout_duration"  yaml:"timeout_duration"                  json:"timeout_duration"` + "`" + `
	PrivateJWTAccessTokenSecret  string ` + "`" + `mapstructure:"private_jwt_access_token_secret"  yaml:"private_jwt_access_token_secret"  json:"private_jwt_access_token_secret"` + "`" + `
	PrivateJWTRefreshTokenSecret string ` + "`" + `mapstructure:"private_jwt_refresh_token_secret" yaml:"private_jwt_refresh_token_secret" json:"private_jwt_refresh_token_secret"` + "`" + `
}
`

// ── global/errors.go ─────────────────────────────────────────────────────────

var tmplGlobalErrors = `package global

import "errors"

var (
	ErrInternalServer = errors.New("internal server error")
	ErrNotFound       = errors.New("item not found")
	ErrConflict       = errors.New("item already exists")
	ErrBadInput       = errors.New("invalid input")
)

type BadResponse struct {
	Code    int    ` + "`" + `json:"code"` + "`" + `
	Message string ` + "`" + `json:"message"` + "`" + `
}

type SuccessResponse struct {
	Code    int         ` + "`" + `json:"code"` + "`" + `
	Message string      ` + "`" + `json:"message"` + "`" + `
	Data    interface{} ` + "`" + `json:"data"` + "`" + `
}
`

// ── global/global.go ─────────────────────────────────────────────────────────

var tmplGlobalGlobal = `package global

import "time"

type PostgresDefault struct {
	UpdatedAt time.Time ` + "`" + `json:"updated_at,omitempty"` + "`" + `
	CreatedAt time.Time ` + "`" + `json:"created_at,omitempty"` + "`" + `
	DeletedAt time.Time ` + "`" + `json:"deleted_at,omitempty"` + "`" + `
	UpdatedBy string    ` + "`" + `json:"updated_by,omitempty"` + "`" + `
	DeletedBy string    ` + "`" + `json:"deleted_by,omitempty"` + "`" + `
}

type ResponseError struct {
	Message string ` + "`" + `json:"message"` + "`" + `
}

type ResponseSuccess struct {
	Message string ` + "`" + `json:"message"` + "`" + `
}

type TokenResponse struct {
	AccessToken  string    ` + "`" + `json:"access_token"` + "`" + `
	RefreshToken string    ` + "`" + `json:"refresh_token"` + "`" + `
	ExpiredAt    time.Time ` + "`" + `json:"expired_at"` + "`" + `
}
`

// ── middlewares/middleware.go ─────────────────────────────────────────────────

var tmplMiddleware = `package middlewares

import (
	"net/http"
	"strings"

	"{{.ModuleName}}/global"
	"{{.ModuleName}}/utils/token"

	"github.com/golang-jwt/jwt/v5"
	"github.com/labstack/echo/v4"
)

type GoMiddlewareInterface interface {
	ValidateCORS(next echo.HandlerFunc) echo.HandlerFunc
	ValidateToken(next echo.HandlerFunc) echo.HandlerFunc
}

type GoMiddleware struct {
	AccessSecret []byte
}

func InitMiddleware(accessSecret []byte) GoMiddlewareInterface {
	return &GoMiddleware{AccessSecret: accessSecret}
}

func (gm *GoMiddleware) ValidateCORS(next echo.HandlerFunc) echo.HandlerFunc {
	return func(c echo.Context) error {
		c.Response().Header().Set("Access-Control-Allow-Origin", "*")
		return next(c)
	}
}

func (gm *GoMiddleware) ValidateToken(next echo.HandlerFunc) echo.HandlerFunc {
	return func(c echo.Context) error {
		authHeader := c.Request().Header.Get("Authorization")
		if authHeader == "" {
			return c.JSON(http.StatusUnauthorized, global.BadResponse{
				Code:    http.StatusUnauthorized,
				Message: "Authorization header is missing",
			})
		}

		parts := strings.Split(authHeader, " ")
		if len(parts) != 2 || strings.ToLower(parts[0]) != "bearer" {
			return c.JSON(http.StatusUnauthorized, global.BadResponse{
				Code:    http.StatusUnauthorized,
				Message: "Invalid Authorization header format",
			})
		}

		accessToken := parts[1]
		claims := &token.Claims{}
		parsedToken, err := jwt.ParseWithClaims(accessToken, claims, func(t *jwt.Token) (interface{}, error) {
			return gm.AccessSecret, nil
		})

		if err != nil || !parsedToken.Valid {
			return c.JSON(http.StatusUnauthorized, global.BadResponse{
				Code:    http.StatusUnauthorized,
				Message: "Invalid access token",
			})
		}
		return next(c)
	}
}
`

// ── models/dto.go ────────────────────────────────────────────────────────────

// ── api/example.proto ────────────────────────────────────────────────────────
// This is the seed proto for the example module generated by `a-kit create`.
// Users copy this pattern to api/<module>.proto and run `a-kit generate`.

var tmplExampleProto = `syntax = "proto3";

package example;

// ExampleService manages example resources.
//
// Route annotations (optional — overrides name-based inference):
//   rpc Foo(FooReq) returns (FooResp) GET  /path;
//   rpc Foo(FooReq) returns (FooResp) POST /path/:id/action;
//
// Without an annotation the HTTP method and path are inferred from the RPC name:
//   Create* → POST /examples          List*   → GET  /examples
//   Get*    → GET  /examples/:id      Update* → PUT  /examples/:id
//   Delete* → DELETE /examples/:id    other   → POST /<rpc-name>
//
// Mark an RPC "Internal" to generate it in internal/example/ with no HTTP handler.
service ExampleService {
  rpc CreateExample(CreateExampleRequest)           returns (CreateExampleResponse);                      // POST   /examples
  rpc GetExample(GetExampleRequest)                 returns (GetExampleResponse);                         // GET    /examples/:id
  rpc ListExample(ListExampleRequest)               returns (ListExampleResponse);                        // GET    /examples
  rpc UpdateExample(UpdateExampleRequest)           returns (UpdateExampleResponse);                      // PUT    /examples/:id
  rpc DeleteExample(DeleteExampleRequest)           returns (DeleteExampleResponse);                      // DELETE /examples/:id
  rpc SearchExample(SearchExampleRequest)           returns (SearchExampleResponse) GET /examples/search; // explicit GET /examples/search
  rpc ApproveExample(ApproveExampleRequest)         returns (ApproveExampleResponse) POST /examples/:id/approve; // explicit POST with path param
  rpc RecalculateExample(RecalculateExampleRequest) returns (RecalculateExampleResponse) Internal;        // domain-only, no HTTP
}

message CreateExampleRequest {
  string name = 1;
  string description = 2;
}

message CreateExampleResponse {
  string id = 1;
  string name = 2;
  string description = 3;
}

message GetExampleRequest {
  string id = 1;
}

message GetExampleResponse {
  string id = 1;
  string name = 2;
  string description = 3;
}

message ListExampleRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message ListExampleResponse {
  repeated GetExampleResponse items = 1;
  int32 total = 2;
}

message UpdateExampleRequest {
  string id = 1;
  string name = 2;
  string description = 3;
}

message UpdateExampleResponse {
  string id = 1;
  string name = 2;
  string description = 3;
}

message DeleteExampleRequest {
  string id = 1;
}

message DeleteExampleResponse {
  bool success = 1;
}

message SearchExampleRequest {
  string query = 1;
  int32 page = 2;
}

message SearchExampleResponse {
  repeated GetExampleResponse items = 1;
  int32 total = 2;
}

message ApproveExampleRequest {
  string id = 1;
}

message ApproveExampleResponse {
  bool success = 1;
}

message RecalculateExampleRequest {
  string id = 1;
}

message RecalculateExampleResponse {
  bool success = 1;
}
`

// ── utils/common/common.go ───────────────────────────────────────────────────

var tmplUtilsCommon = `package common

import "strings"

// ToSnakeCase converts a camelCase string to snake_case.
func ToSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteByte('_')
			}
			result.WriteRune(r + 32)
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}
`

// ── utils/common/uuid.go ─────────────────────────────────────────────────────

var tmplUtilsUUID = `package common

import "github.com/google/uuid"

// NewUUID generates a new UUID string.
func NewUUID() string {
	return uuid.New().String()
}

// IsValidUUID returns true if the given string is a valid UUID.
func IsValidUUID(u string) bool {
	_, err := uuid.Parse(u)
	return err == nil
}
`

// ── utils/token/token.go ─────────────────────────────────────────────────────

var tmplUtilsToken = `package token

import (
	"time"

	"github.com/golang-jwt/jwt/v5"
)

// Claims defines the JWT claims structure.
type Claims struct {
	UserID string ` + "`" + `json:"user_id"` + "`" + `
	Email  string ` + "`" + `json:"email"` + "`" + `
	jwt.RegisteredClaims
}

// GenerateAccessToken creates a signed JWT access token.
func GenerateAccessToken(userID, email string, secret []byte, expiry time.Duration) (string, time.Time, error) {
	expiredAt := time.Now().Add(expiry)
	claims := &Claims{
		UserID: userID,
		Email:  email,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(expiredAt),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		},
	}
	t := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	signed, err := t.SignedString(secret)
	return signed, expiredAt, err
}

// ParseToken parses and validates a JWT token string.
func ParseToken(tokenStr string, secret []byte) (*Claims, error) {
	claims := &Claims{}
	t, err := jwt.ParseWithClaims(tokenStr, claims, func(token *jwt.Token) (interface{}, error) {
		return secret, nil
	})
	if err != nil || !t.Valid {
		return nil, err
	}
	return claims, nil
}
`

// ── utils/validator/validator.go ─────────────────────────────────────────────

var tmplUtilsValidator = `package validator

import (
	"fmt"
	"strings"

	"github.com/go-playground/validator/v10"
)

var validate = validator.New()

// ValidateStruct validates a struct using its validate tags.
func ValidateStruct(s interface{}) error {
	if err := validate.Struct(s); err != nil {
		var errs []string
		for _, e := range err.(validator.ValidationErrors) {
			errs = append(errs, fmt.Sprintf("field %s failed on '%s' rule", e.Field(), e.Tag()))
		}
		return fmt.Errorf("%s", strings.Join(errs, "; "))
	}
	return nil
}
`

// ── mysql/sqitch.conf ────────────────────────────────────────────────────────

var tmplSqitchConf = `[core]
	engine = mysql
	plan_file = sqitch.plan
	top_dir = .

[engine "mysql"]
	target = db:mysql://root@localhost/{{.PackageName}}
`

// ── mysql/sqitch.plan ────────────────────────────────────────────────────────

var tmplSqitchPlan = `%syntax-version=1.0.0
%project={{.PackageName}}
%uri=https://github.com/yourusername/{{.ProjectName}}

`

// ── utils/config/config.go ──────────────────────────────────────────────────

var tmplUtilsConfig = `package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

// envPattern matches {{"{{VAR_NAME}}"}} and {{"{{VAR_NAME:default_value}}"}} placeholders.
var envPattern = regexp.MustCompile(` + "`" + `\{\{([A-Z0-9_]+)(?::([^}]*))?\}\}` + "`" + `)

// Load reads the config file specified by the APP_CONFIG environment variable
// (defaults to "config.yaml") and unmarshals it into out.
// Placeholders of the form {{"{{VAR_NAME}}"}} or {{"{{VAR_NAME:default}}"}} are replaced
// with the corresponding environment variable value before parsing.
func Load(out interface{}) error {
	path := os.Getenv("APP_CONFIG")
	if path == "" {
		path = "config.yaml"
	}
	return LoadFile(path, out)
}

// LoadFile reads the file at path, substitutes env var placeholders, and
// unmarshals the result into out. Supported extensions: .yaml, .yml, .json.
func LoadFile(path string, out interface{}) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("config: read %q: %w", path, err)
	}
	substituted := substitute(string(data))
	switch strings.ToLower(filepath.Ext(path)) {
	case ".yaml", ".yml":
		return yaml.Unmarshal([]byte(substituted), out)
	case ".json":
		return json.Unmarshal([]byte(substituted), out)
	default:
		return fmt.Errorf("config: unsupported file extension %q (use .yaml, .yml, or .json)", filepath.Ext(path))
	}
}

// substitute replaces all {{"{{VAR}}"}} and {{"{{VAR:default}}"}} placeholders in s with
// the value of the named environment variable, falling back to the default.
func substitute(s string) string {
	return envPattern.ReplaceAllStringFunc(s, func(match string) string {
		groups := envPattern.FindStringSubmatch(match)
		varName, defaultVal := groups[1], groups[2]
		if val := os.Getenv(varName); val != "" {
			return val
		}
		return defaultVal
	})
}
`

// ── config.yaml ─────────────────────────────────────────────────────────────
// Committed to the repo — contains only {{VAR:default}} placeholders, no
// plaintext secrets. Secrets always come from environment variables.

var tmplConfigYAML = `# Application configuration
# Syntax: {{"{{VAR_NAME}}"}} injects the environment variable VAR_NAME.
#         {{"{{VAR_NAME:default}}"}} falls back to "default" when the variable is unset.
# Override which file is loaded by setting APP_CONFIG (e.g. APP_CONFIG=config/prod.yaml).

host_url: "{{"{{HOST_URL:http://localhost}}"}}"
host_port: "{{"{{APP_PORT:9000}}"}}"

db_host: "{{"{{DB_HOST:localhost}}"}}"
db_port: "{{"{{DB_PORT:3306}}"}}"
db_name: "{{"{{DB_NAME:"}}{{.PackageName}}{{"}}"}}"
db_user: "{{"{{DB_USER:root}}"}}"
db_pass: "{{"{{DB_PASSWORD}}"}}"

timeout_duration: 30

private_jwt_access_token_secret:  "{{"{{JWT_SECRET:change-me-in-production}}"}}"
private_jwt_refresh_token_secret: "{{"{{JWT_REFRESH_SECRET:change-me-in-production}}"}}"
`

// ── config.json.example ──────────────────────────────────────────────────────
// JSON alternative — copy to config.json and set APP_CONFIG=config.json to use.

var tmplConfigJSON = `{
  "_comment": "Syntax: {{"{{VAR_NAME}}"}} injects an env var. {{"{{VAR_NAME:default}}"}} provides a fallback.",
  "_hint":    "Set APP_CONFIG=config.json (or any path) to switch config files.",

  "host_url":  "{{"{{HOST_URL:http://localhost}}"}}", 
  "host_port": "{{"{{APP_PORT:9000}}"}}", 

  "db_host": "{{"{{DB_HOST:localhost}}"}}", 
  "db_port": "{{"{{DB_PORT:3306}}"}}", 
  "db_name": "{{"{{DB_NAME:"}}{{.PackageName}}{{"}}"}}", 
  "db_user": "{{"{{DB_USER:root}}"}}", 
  "db_pass": "{{"{{DB_PASSWORD}}"}}", 

  "timeout_duration": 30,

  "private_jwt_access_token_secret":  "{{"{{JWT_SECRET:change-me-in-production}}"}}", 
  "private_jwt_refresh_token_secret": "{{"{{JWT_REFRESH_SECRET:change-me-in-production}}"}}"}}`

