package scaffold

import "embed"

//go:embed templates
var scaffoldTmplFS embed.FS

func mustScaffoldTmpl(name string) string {
b, err := scaffoldTmplFS.ReadFile("templates/" + name)
if err != nil {
panic("a-kit: missing scaffold template " + name + ": " + err.Error())
}
return string(b)
}

// projectFiles returns a map of file path -> template string for the new project.
// The example module files are NOT listed here — they are generated by the proto
// generator (same engine as `a-kit generate`) from api/example.proto.
func projectFiles(data templateData) map[string]string {
return map[string]string{
"go.mod":             mustScaffoldTmpl("go.mod.tmpl"),
"main.go":            mustScaffoldTmpl("main.go.tmpl"),
".gitignore":         mustScaffoldTmpl("gitignore.tmpl"),
"Dockerfile":         mustScaffoldTmpl("Dockerfile.tmpl"),
"docker-compose.yml": mustScaffoldTmpl("docker-compose.yml.tmpl"),
"Makefile":           mustScaffoldTmpl("Makefile.tmpl"),
"README.md":          mustScaffoldTmpl("README.md.tmpl"),

// global
"global/configuration.go": mustScaffoldTmpl("global_configuration.go.tmpl"),
"global/errors.go":        mustScaffoldTmpl("global_errors.go.tmpl"),
"global/global.go":        mustScaffoldTmpl("global_global.go.tmpl"),

// middlewares
"middlewares/middleware.go": mustScaffoldTmpl("middleware.go.tmpl"),

// utils
"utils/common/common.go":       mustScaffoldTmpl("utils_common.go.tmpl"),
"utils/common/uuid.go":         mustScaffoldTmpl("utils_uuid.go.tmpl"),
"utils/token/token.go":         mustScaffoldTmpl("utils_token.go.tmpl"),
"utils/validator/validator.go": mustScaffoldTmpl("utils_validator.go.tmpl"),
"utils/config/config.go":       mustScaffoldTmpl("utils_config.go.tmpl"),

// config files
"config.yaml":         mustScaffoldTmpl("config.yaml.tmpl"),
"config.json.example": mustScaffoldTmpl("config.json.tmpl"),

// mysql sqitch
"mysql/sqitch.conf": mustScaffoldTmpl("sqitch_conf.tmpl"),
"mysql/sqitch.plan": mustScaffoldTmpl("sqitch_plan.tmpl"),

// proto definition — the example module is generated from this
"api/example.proto": mustScaffoldTmpl("example.proto.tmpl"),
}
}
